### ISSUE TITLE
抓雪球时报告速度过快

### ISSUE THREAD

**Issue by linkerlin** [ryh95/pyspider-stock#2]
{
  "content": "{\"error_description\":\"您的请求过于频繁，请稍后再试\",\"error_uri\":\"/statuses/search.json\",\"error_code\":\"22612\"}", 
  "encoding": null, 
  "error": "HTTP 400: Bad Request", 
  "headers": {
    "Cache-Control": "private, no-store, no-cache, must-revalidate, max-age=0", 
    "Connection": "keep-alive", 
    "Content-Type": "application/json;charset=UTF-8", 
    "Date": "Sat, 27 May 2017 04:19:58 GMT", 
    "P3p": "\"CP=\"IDC DSP COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT\"\"", 
    "Server": "openresty/1.11.2.1", 
    "Strict-Transport-Security": "max-age=31536000", 
    "Trace-Id": "58a863cd89fab695", 
    "Transfer-Encoding": "chunked", 
    "X-Errorcode": "22612", 
    "X-Http-Reason": "Bad Request"
  }, 
  "ok": false, 
  "redirect_url": "https://xueqiu.com/statuses/search.json?count=10&comment=0&symbol=SH000003&hl=0&source=user&sort=time&page=78&_=1495858798955", 
  "status_code": 400, 
  "time": 0.17786097526550293
}

**Comment by ryh95** [comment]
哦豁 有可能是雪球出了反爬虫的东西，我以前爬的时候好像设的是80/20也没问题，你的速度设了多少？（web页面上可以调整的），如果很慢还是报了这个错的话，我后面想想办法

**Comment by linkerlin** [comment]
我就是按默认的1/3爬的，雪球应该是用页面中的js是否执行来判断的吧。

**Comment by ryh95** [comment]
那有可能是反爬虫的东西，我后面修改下代码

**Comment by ryh95** [comment]
我跑了下雪球的script，能够获取数据但是要不了多久就400了，这说明我的雪球爬虫script没有问题因为mongoDB中有数据，另一方面我试了0.1/1这样很慢的速度还是被封了，所以可能要用IP池或者其他方法来绕过检测，不过这个不在本项目探讨范围内，如果没有其他问题这个case就close了
